// <auto-generated />
namespace PizzaShop.Migrations.Cms
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Eventchangeproperty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Eventchangeproperty));
        
        string IMigrationMetadata.Id
        {
            get { return "201703022122220_Event change property"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
