// <auto-generated />
namespace PizzaShop.Migrations.Cms
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class AddpropertyControllerName : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddpropertyControllerName));
        
        string IMigrationMetadata.Id
        {
            get { return "201702131534148_Add property ControllerName"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
