// <auto-generated />
namespace PizzaShop.Migrations.PizzaShopMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changes_1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changes_1));
        
        string IMigrationMetadata.Id
        {
            get { return "201704122027122_Changes_1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
