// <auto-generated />
namespace PizzaShop.Migrations.PizzaShopMigration
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Saladpricechangeprecision : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Saladpricechangeprecision));
        
        string IMigrationMetadata.Id
        {
            get { return "201702132023000_Salad price change precision"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
